spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:E:/Informatyka/Java/Spring/todo/todo-app/todo-db'
    username: 'sa'
    password: 'sa'
  flyway.baselineOnMigrate: true
  jpa:
    hibernate.ddl-auto: validate




